spring.application.name=HotelManagement_BE
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME:hotelmanagement}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1111}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Cloudinary Configuration
cloudinary.cloud-name=${CLOUD_NAME:ddkokspkn}
cloudinary.api-key=${CLOUD_API_KEY:512282478985427}
cloudinary.api-secret=${CLOUD_API_SECRET:IZdA5ZW83PMvn4aeBMBuhgX2Q7k}

# Multipart Upload Limit
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method

# Security JWT
application.security.jwt.secret-key=${JWT_SECRET:8f3d1b6a7c9e0f2a4b8c6d1e3f5a7b9c0d2e4f6a8b1c3d5e7f9a0b2c4d6e8f1a}
application.security.jwt.expiration=86400000
server.max-http-request-header-size=48KB

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${NAME_EMAIL:lengocdung8019@gmail.com}
spring.mail.password=${MAIL_PASSWORD:lqma aihq bfmu qsuy}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


#pos
CLIENT_ID=6f697811-e048-4d25-ab1d-333b58648b66
API_KEY=5e6a9fd2-bb50-4f91-9b6a-4a437d0dd5e0
CHECKSUM_KEY=78c40471d51a1a1e097c020df3ba120b889d109c9d4592d5fdf2c2ce83e08383
payos.client-id=${CLIENT_ID}
payos.api-key=${API_KEY}
payos.checksum-key=${CHECKSUM_KEY}
